In [3]:
#建立list
a = [1, 3, 5, 7, 9]
a * 2

b = [2, 4, 6, 8 ,10]
a + b

result = []
for i in range(5):
    result.append(a[i] + b[i])

result

[3, 7, 11, 15, 19]

In [4]:
import numpy as np

#透過list建立ndArray

a_array = np.array([1, 3, 5, 7, 9])
a_array * 2

b_array = np.array([2, 4, 6, 8 ,10])

a_array + b_array

array([ 3,  7, 11, 15, 19])

In [5]:
#使用python建立5個亂數元素的list
import random

#list comprehension
[random.randint(50,100) for _ in range(5)]

[97, 93, 86, 83, 54]

In [6]:
#使用numpy random 建立亂數
import numpy as np
np.random.randint(50,high=100,size=5)

array([62, 57, 91, 70, 66])

In [7]:
np.random.randint(50,high=100,size=(50, 5))

array([[72, 67, 50, 72, 62],
       [79, 95, 55, 85, 72],
       [76, 54, 69, 89, 79],
       [92, 54, 83, 58, 99],
       [68, 50, 83, 88, 97],
       [87, 58, 87, 54, 95],
       [62, 60, 52, 87, 68],
       [53, 91, 53, 97, 57],
       [79, 63, 62, 63, 85],
       [89, 71, 51, 64, 89],
       [99, 52, 74, 53, 74],
       [93, 92, 84, 68, 85],
       [75, 99, 75, 97, 97],
       [74, 82, 98, 92, 63],
       [65, 85, 73, 76, 84],
       [95, 67, 58, 83, 68],
       [87, 59, 52, 90, 80],
       [53, 54, 71, 89, 92],
       [84, 71, 72, 81, 67],
       [66, 63, 67, 63, 90],
       [72, 78, 59, 72, 85],
       [95, 75, 97, 67, 61],
       [89, 83, 98, 85, 57],
       [51, 56, 92, 64, 93],
       [52, 88, 87, 71, 97],
       [75, 58, 98, 99, 67],
       [50, 77, 65, 70, 86],
       [74, 83, 62, 50, 54],
       [96, 86, 51, 63, 50],
       [99, 86, 81, 74, 61],
       [87, 56, 56, 75, 77],
       [95, 68, 81, 75, 61],
       [51, 79, 61, 81, 76],
       [92, 58, 72, 79, 98],
       [50, 60